---
  - name: Install epel-release and yum-utils
    yum:
      name: "{{ item }}"
      state: latest
    with_items:
      - epel-release
      - yum-utils
        
  - name: Upload remi repositories
    template: src={{item.src}} dest={{item.dest}} mode=644
    with_items:
      - { src: 'remi.repo', dest: '/etc/yum.repos.d/remi.repo' }
      - { src: 'remi-php72.repo', dest: '/etc/yum.repos.d/remi-php72.repo' }
      - { src: 'remi-safe.repo', dest: '/etc/yum.repos.d/remi-safe.repo' }
      - { src: 'RPM-GPG-KEY-remi', dest: '/etc/pki/rpm-gpg/RPM-GPG-KEY-remi' }
        
  - name: Install nginx
    yum:
      name: nginx
      state: latest
    
  - name: Start and enable nginx
    service:
      name: nginx
      state: started
      enabled: yes
 
  - name: Install all php 7.2 supports
    yum:
      name: "{{ item }}"
      state: latest
    with_items:
      - php-cli 
      - php-fpm 
      - php-mysql
      - php-json
      - php-opcache
      - php-mbstring
      - php-xml
      - php-gd 
      - php-curl
      - git

  - name: Copy/Backup /etc/php-fpm.d/www.conf and /etc/php.ini
    copy: src={{ item.src }} dest={{ item.dest}}
    with_items:
      - { src: '/etc/php-fpm.d/www.conf', dest: '/etc/php-fpm.d/www.conf.bak' }
      - { src: '/etc/php.ini', dest: '/etc/php.ini.bak' }
      
  - name: Update /etc/php-fpm.d/www.conf
    replace:
      path: /etc/php-fpm.d/www.conf
      regexp: "{{ item.regexp }}"
      replace: "{{ item.replace }}"
    with_items:
      - { regexp: 'user = apache',  replace: 'user = nginx' }
      - { regexp: 'group = apache', replace: 'group = nginx' }
      - { regexp: 'listen = 127.0.0.1:9000', replace: 'listen = /run/php-fpm/www.sock' }
      - { regexp: ';listen.owner = nobody', replace: 'listen.owner = nginx' }
      - { regexp: ';listen.group = nobody', replace: 'listen.group = nginx' }
      
  - name: Update /etc/php.ini
    replace:
      path: /etc/php.ini
      regexp: ';cgi.fix_pathinfo=1'
      replace: 'cgi.fix_pathinfo=0'

  - name: Change owner /var/lib/php
    file:
      path: /var/lib/php
      owner: root
      group: nginx
      recurse: yes 
 
  - name: Start and enable php-fpm
    service:
      name: php-fpm
      state: restarted
      enabled: yes
      
